def print_help():
    print("Commands:")
    print("p - play selected to cut part of the track")
    print("b <ms> - set beginning of the sample")
    print("l <ms> - set length of the sample")
    print("s <ms> - set step for forward and rewind")
    print("f - forward. You can use multiple f's to fast forward (e.g. fff - fast forward 3 times)")
    print("r - rewind. You can use multiple r's to rewind (e.g. rrr - rewind 3 times)")
    print("plot - plot amplitude of the selected part of the track")
    print("info - print information about cutting the track")
    print("load <filepath> - change the track to cut")
    print("cut - cut the track")
    print("cut -a - cut the track and adjust the cut position")
    print("am - automix the whole track from the beginning to the end with the current sample length and algorithm")
    print("amc info - show information about automix configuration")
    print("amc m <algorithm> s <playback_speed> l </ or *number> - set automix params")
    print("set_wav_enabled - enable wav export")
    print("set_wav_disabled - disable wav export")
    print("set_verbose_enabled - enable verbose mode")
    print("set_verbose_disabled - disable verbose mode")
    print("help - print this help message")
    print("q - quit")